services: 
  fastapi:
    build: 
      context: .
      dockerfile: Dockerfile
    image: initcron/fastapi:dev
    ports: 
      - "8000:8000"
  
  streamlit: 
    image: initcron/streamlit:dev
    build: 
      context: streamlit_app
      # Use the Dockerfile in the streamlit_app directory
      dockerfile: Dockerfile
    ports: 
      - "8501:8501"
    environment:
      - API_URL=http://fastapi:8000
    
